import { Link } from 'react-router-dom';

export default function HomePage() {
  return (
    <div className="home-page">
      <section className="hero-section">
        <div className="container hero-content">
          <span className="eyebrow">DFS / BFS Algorithms</span>
          <h2 className="hero-title">Welcome to the Maze Game</h2>
          <p className="hero-subtitle">
            Navigate from the start to the end using your keyboard. Once you reach the destination, the optimal path generated by Breadth-First Search (BFS) will be revealed.
          </p>
          <div className="hero-cta">
            <Link className="primary-btn hero-btn" to="/play">Play Maze Now</Link>
          </div>
        </div>
      </section>

      <section className="features-section">
        <div className="container">
          <h3 className="section-title">Game Features</h3>
          <div className="features-grid">
            <div className="feature-card">
              <h4>DFS Generation</h4>
              <p>Randomly generated mazes using Depth-First Search for infinite replayability.</p>
            </div>
            <div className="feature-card">
              <h4>Complexity Loops</h4>
              <p>Multiple alternative paths added so it's not just a single strict corridor.</p>
            </div>
            <div className="feature-card">
              <h4>Interactive Play</h4>
              <p>Lightning fast responsive keyboard gameplay via W, A, S, D controls.</p>
            </div>
            <div className="feature-card">
              <h4>BFS Solver</h4>
              <p>Automatic shortest-path detection using Breadth-First Search logic on completion.</p>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}
